server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db?createDatabaseIfNotExist=true
    username: root
    password: Subhadip@2005
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: dGFza2Zsb3ctc3VwZXItc2VjcmV0LWtleS1jaGFuZ2UtdGhpcy1sYXRlci0xMjM0NTY=
  expiration-ms: 3600000